# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpytheme: jekyll-theme-chirpy

lang: zh-CN
timezone: Asia/Shanghai

title: fkkkt的字纸篓
tagline: 全栈不开发者
description: >-
  有的没的都搞里头

url: "https://fkkkt.github.io"

github:
  username: fkkkt

social:
  name: fkkkt
  links:
    - https://github.com/fkkkt

paginate: 5

comments:
  active: false

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-seo-tag
